# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: change dir
        run: |
          rm -rf .git
          mkdir -p data
      - name: git pull
        run: |
          cd data
          git clone https://github.com/deliangyang/chi-api-doc.git
      - name: push repos
        run: |
          cd data
          git checkout -b master
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git config --global user.name 'sntfly'
          git config --global user.email 'yang623601391@gmail.com'
          git push --set-upstream origin gh-pages -f
